# LOGS
quarkus.log.level=INFO
quarkus.log.category."io.synkronize".level=TRACE

# VERT.X
quarkus.vertx.event-loops-pool-size=1
quarkus.thread-pool.max-threads=5
quarkus.vertx.internal-blocking-pool-size=1

# JSON LOGS
quarkus.log.json.console.enable=false
quarkus.log.json.fields.hostname.enabled=false
quarkus.log.json.fields.sequence.enabled=false
quarkus.log.json.fields.logger-class-name.enabled=false
quarkus.log.json.fields.thread-id.enabled=false
quarkus.log.json.fields.process-id.enabled=false
quarkus.log.json.fields.process-name.enabled=false
quarkus.log.json.fields.mdc.flat-fields=true

# MICROMETER
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/metrics

# HTTP
quarkus.http.port=8080

# ---------- SYNKRONIZE ---------- #
synkronize.scheduler.thread-count=10
synkronize.heartbeats.enabled=false

# BUFFER
synkronize.buffer.type=${BUFFER_TYPE:console}
synkronize.buffer.kafka.bootstrap-servers=localhost:9092
synkronize.buffer.kafka.topic=synkronize-messages
synkronize.buffer.kafka.client-id=synkronize-scheduler

synkronize.address-resolver.strategy=${ADDRESS_RESOLVER_STRATEGY:local}
# -------------------------------- #