# QUARKUS MONGODB EXT
quarkus.mongodb.devservices.enabled=false

# LOGS
quarkus.log.level=INFO
quarkus.log.category."io.synkronize".min-level=TRACE
quarkus.log.category."io.synkronize".level=TRACE

# JSON LOGS
quarkus.log.json.console.enable=false
quarkus.log.json.fields.hostname.enabled=false
quarkus.log.json.fields.sequence.enabled=false
quarkus.log.json.fields.logger-class-name.enabled=false
quarkus.log.json.fields.thread-id.enabled=false
quarkus.log.json.fields.process-id.enabled=false
quarkus.log.json.fields.process-name.enabled=false
quarkus.log.json.fields.mdc.flat-fields=true

# MICROMETER
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/metrics

# HTTP
quarkus.http.port=8081

# ---------- SYNKRONIZE ---------- #
synkronize.buffer.type=${BUFFER_TYPE:mock}
synkronize.buffer.kafka.bootstrap-servers=localhost:9092
synkronize.buffer.kafka.topic=synkronize-messages
synkronize.buffer.kafka.group-id=synkronize-executor
synkronize.buffer.kafka.client-id=synkronize-executor

# Initial in-memory sink config provider.
# TODO Replace this by a MongoDB-backed provider.

# -------------------------------- #
