syntax = "proto3";

import "google/protobuf/empty.proto";

option java_multiple_files = true;
option java_package = "io.synkronize.scheduler.api.grpc.contract";
option java_outer_classname = "TaskCreation";

package io.synkronize;

service TaskGrpcService {
  rpc StartTask (CreateTaskMessage) returns (google.protobuf.Empty);
  rpc StopTask (StopTaskMessage) returns (google.protobuf.Empty);
}

message CreateTaskMessage {

  string env_id = 1;
  string task_id = 2;
  string source_id = 3;
  string source_type = 4;
  string message_type = 5;
  map<string, string> config_map = 6;
}

message StopTaskMessage {

  string env_id = 1;
  string task_id = 2;
}